server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.183.131
  rabbitmq:
    host: 192.168.183.131
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.leyou.user.pojo